import bcrypt from 'bcryptjs'

const data={
    users:[
      {
        name:'Phoenix',
        email:'my123@qq.com',
        password:bcrypt.hashSync('123456'),//加密数据库密码
        isAdmin:true,
      },
      {
        name:'James',
        email:'your123@qq.com',
        password:bcrypt.hashSync('123456'),
        isAdmin:false,
      },
    ],
    products: [
        {
          name: 'Free Shirt',
          slug: 'free-shirt',
          category: '衬衫',
          image: '/images/shirt1.jpg',
          price: 70,
          brand: 'Nike',
          rating: 4.5,
          numReviews: 8,
          countInStock: 20,
          description: '一件流行的衬衫',
          isFeatured: true,
          banner: '/images/banner1.jpg',
        },
        {
          name: 'Fit Shirt',
          slug: 'fit-shirt',
          category: '衬衫',
          image: '/images/shirt2.jpg',
          price: 80,
          brand: 'Adidas',
          rating: 3.2,
          numReviews: 10,
          countInStock: 20,
          description: '一件流行的衬衫',
          isFeatured: true,
          banner: '/images/banner2.jpg',
        },
        {
          name: 'Slim Shirt',
          slug: 'slim-shirt',
          category: '衬衫',
          image: '/images/shirt3.jpg',
          price: 90,
          brand: 'Raymond',
          rating: 4.5,
          numReviews: 3,
          countInStock: 20,
          description: '一件流行的衬衫',
        },
        {
          name:  'Golf Pants',
          slug: 'golf-pants',
          category: '裤子',
          image: '/images/pants1.jpg',
          price: 90,
          brand: 'Oliver',
          rating: 2.9,
          numReviews: 13,
          countInStock: 20,
          description: '看起来很不错的裤子',
        },
        {
          name: 'Fit Pants',
          slug: 'fit-pants',
          category: '裤子',
          image: '/images/pants2.jpg',
          price: 95,
          brand: 'Zara',
          rating: 3.5,
          numReviews: 7,
          countInStock: 20,
          description: '一件流行短袖',
        },
        {
          name: 'Classic Pants',
          slug: 'classic-pants',
          category: '裤子',
          image: '/images/pants3.jpg',
          price: 75,
          brand: 'Nike',
          rating: 2.4,
          numReviews: 14,
          countInStock: 20,
          description: '一件流行短袖',
        },
      ],
}
export default data;